name: Release

on:
  push:
    tags:
      - "v*.*.*" # Trigger on existing tags

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release notes
        id: release_notes
        uses: orhun/git-cliff-action@v3
        with:
          config: .github/cliff.toml
          args: --latest --strip header

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: ${{ steps.release_notes.outputs.content }}
          draft: false
          prerelease: false

  release:
    name: Release - ${{ matrix.platform.release_for }}
    needs: create-release
    strategy:
      matrix:
        platform:
          - release_for: Linux-x86_64
            os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: emu
            name: emu-Linux-x86_64.tar.gz
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: emu.exe
            name: emu-Windows-x86_64.zip
            command: build

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: emu
            name: emu-Darwin-x86_64.tar.gz
            command: build

          - release_for: macOS-aarch64
            os: macOS-latest
            target: aarch64-apple-darwin
            bin: emu
            name: emu-Darwin-aarch64.tar.gz
            command: build

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: Build binary
        run: |
          cargo build --release --target ${{ matrix.platform.target }}

      - name: Prepare binaries (Windows)
        if: matrix.platform.os == 'windows-latest'
        run: |
          cd target/${{ matrix.platform.target }}/release
          7z a ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          cd -

      - name: Prepare binaries (Unix)
        if: matrix.platform.os != 'windows-latest'
        run: |
          cd target/${{ matrix.platform.target }}/release
          tar czvf ../../../${{ matrix.platform.name }} ${{ matrix.platform.bin }}
          cd -

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.platform.name }}
          asset_name: ${{ matrix.platform.name }}
          tag: ${{ github.ref }}

  homebrew:
    needs: [create-release, release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout emu repository
        uses: actions/checkout@v4
        with:
          path: emu

      - name: Checkout emu-tap repository
        uses: actions/checkout@v4
        with:
          repository: wasabeef/homebrew-emu-tap
          token: ${{ secrets.HOMEBREW_GITHUB_TOKEN }}
          path: emu-tap

      - name: Wait for release assets
        run: sleep 60

      - name: Update Homebrew formula
        run: |
          cd emu
          VERSION=${{ github.ref_name }}
          VERSION_NUM=${VERSION#v}

          echo "Version: $VERSION"
          echo "Version number: $VERSION_NUM"

          # Download and calculate SHA256
          echo "Calculating SHA256 for each platform..."

          MACOS_ARM64_URL="https://github.com/wasabeef/emu/releases/download/${VERSION}/emu-Darwin-aarch64.tar.gz"
          MACOS_X86_URL="https://github.com/wasabeef/emu/releases/download/${VERSION}/emu-Darwin-x86_64.tar.gz"
          LINUX_X86_URL="https://github.com/wasabeef/emu/releases/download/${VERSION}/emu-Linux-x86_64.tar.gz"

          echo "URLs:"
          echo "  macOS ARM64: $MACOS_ARM64_URL"
          echo "  macOS x86_64: $MACOS_X86_URL"
          echo "  Linux x86_64: $LINUX_X86_URL"

          # Download files with retry and calculate SHA256
          echo "Downloading release assets..."

          # Function to download with retry
          download_with_retry() {
            local url=$1
            local output=$2
            local max_attempts=5
            local attempt=1
            
            while [ $attempt -le $max_attempts ]; do
              echo "  Attempt $attempt/$max_attempts for $output"
              if curl -sL "$url" -o "$output"; then
                if [ -s "$output" ]; then
                  echo "  ✓ Downloaded $output successfully"
                  return 0
                else
                  echo "  ✗ Downloaded file is empty"
                fi
              else
                echo "  ✗ Download failed"
              fi
              
              if [ $attempt -lt $max_attempts ]; then
                echo "  Waiting 10 seconds before retry..."
                sleep 10
              fi
              attempt=$((attempt + 1))
            done
            
            echo "  ✗ Failed to download after $max_attempts attempts"
            return 1
          }

          # Download each file with retry
          download_with_retry "$MACOS_ARM64_URL" "emu-macos-arm64.tar.gz" || exit 1
          download_with_retry "$MACOS_X86_URL" "emu-macos-x86.tar.gz" || exit 1
          download_with_retry "$LINUX_X86_URL" "emu-linux-x86.tar.gz" || exit 1

          # Calculate SHA256
          MACOS_ARM64_SHA=$(shasum -a 256 emu-macos-arm64.tar.gz | cut -d' ' -f1)
          MACOS_X86_SHA=$(shasum -a 256 emu-macos-x86.tar.gz | cut -d' ' -f1)
          LINUX_X86_SHA=$(shasum -a 256 emu-linux-x86.tar.gz | cut -d' ' -f1)

          # Verify SHA256 values are different
          if [ "$MACOS_ARM64_SHA" = "$MACOS_X86_SHA" ] || [ "$MACOS_ARM64_SHA" = "$LINUX_X86_SHA" ]; then
            echo "ERROR: SHA256 values are identical, which suggests download issues"
            echo "  macOS ARM64: $MACOS_ARM64_SHA"
            echo "  macOS x86_64: $MACOS_X86_SHA"
            echo "  Linux x86_64: $LINUX_X86_SHA"
            exit 1
          fi

          # Clean up downloaded files
          rm -f emu-*.tar.gz

          echo "SHA256 values:"
          echo "  macOS ARM64: $MACOS_ARM64_SHA"
          echo "  macOS x86_64: $MACOS_X86_SHA"
          echo "  Linux x86_64: $LINUX_X86_SHA"

          # Generate formula using printf to avoid heredoc issues
          printf 'class Emu < Formula
            desc "TUI for managing Android emulators and iOS simulators"
            homepage "https://github.com/wasabeef/emu"
            version "%s"
            license "MIT"

            on_macos do
              if Hardware::CPU.arm?
                url "%s"
                sha256 "%s"
              else
                url "%s"
                sha256 "%s"
              end
            end

            on_linux do
              url "%s"
              sha256 "%s"
            end

            def install
              bin.install "emu"
            end

            test do
              assert_match version.to_s, shell_output("#{bin}/emu --version")
            end
          end\n' \
          "$VERSION_NUM" \
          "$MACOS_ARM64_URL" "$MACOS_ARM64_SHA" \
          "$MACOS_X86_URL" "$MACOS_X86_SHA" \
          "$LINUX_X86_URL" "$LINUX_X86_SHA" \
          > ../emu-tap/Formula/emu.rb

          echo "Generated formula:"
          cat ../emu-tap/Formula/emu.rb

      - name: Commit and push formula update
        run: |
          cd emu-tap
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Add timestamp to force update even if content is the same
          echo "" >> Formula/emu.rb
          echo "# Updated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> Formula/emu.rb

          git add Formula/emu.rb
          git commit -m "emu ${{ github.ref_name }}"
          git push
          echo "Formula updated successfully"
